### ISSUE TITLE
bobmon2 fails over when slurmctld is restarted

### ISSUE THREAD

**Issue by chrissamuel** [chanconrad/bobMonitor2#2]
Hi Conrad,

Robin noticed that when I restarted slurmctld to use a patched version to get some extra debug info for SchedMD the bobmon2 process died with:

`May  9 14:19:20 transom1 bobmon2: ValueError: ('Unable to contact slurm controller (connect failure)', 1800)`

He's suggested:
> probably just needs a try/except around the slurm queries and a retry loop with timer backoffs.

cheers!
Chris

**Comment by chanconrad** [comment]
I haven't forgotten about this - will get around to it soon!

**Comment by chanconrad** [comment]
Done!
