### ISSUE TITLE
Enhancement requests

### ISSUE THREAD

**Issue by vivekvenkris** [chanconrad/bobMonitor2#3]
Hi @chanconrad,

I am posting this OzStar HPC support ticket here, following @chrissamuel's request.

I am a regular OzStar user and I was wondering if the following enhancements can be made. 

1. Can we have a summarised status page listing all nodes with their available CPU/GPU and Memory? This would facilitate us while requesting the appropriate resources. For example, if I know a node has 25 free CPUs, I am better off requesting 25 CPUs and starting the job immediately rather than requesting 30 and waiting like a day on the queue. So this information would really help.  Using Ganglia for this is a bit tedious, especially for the average user who has no sys-admin knowledge. 

2. When we click on a user to check their jobs, could you also display the wall time? Many times I see jobs from a single user taking a lot of the resources ( sometime that user is me :P ). So if we have to "srun" a job instead of "sbatch" for several reasons, it would be great if we could guess when the cluster will be free, so that we can schedule accordingly.  

Thanks,
Vivek

**Comment by chanconrad** [comment]
Hi Vivek, 

Thanks for suggesting these features - I think they will be very helpful for many users. It may take me a week or two to get around to implementing them, but I'll let you know as soon as it's done!

Cheers,
Conrad

**Comment by vivekvenkris** [comment]
@chanconrad 

No hurry! Thanks for doing this :)

**Comment by chanconrad** [comment]
I've added an overview of available CPU core counts on the bottom left - have a look and let me know what you think. I could also do the same for GPU and memory, but actually the majority of the time, jobs are held because of insufficient cores.

As for seeing wall times of jobs, this is a little bit more complicated, but I'll get to it soon.

**Comment by vivekvenkris** [comment]
Many thanks @chanconrad 

@chrissamuel, would you be able to install this version? 

Thanks,
Vivek

**Comment by vivekvenkris** [comment]
Oh, I just saw that it is already installed, this is very useful! Awesome. I think memory will still be useful here as many of us run largemem usage codes. Thanks so much for doing this.

**Comment by chanconrad** [comment]
I've added a view, accessed using the button at the bottom left which lets you see all non-empty nodes in detail. Empty nodes aren't shown, but are summarised by a count at the bottom left (e.g. 32 cores on 18 nodes). Changes are now live on the ozstar page. Hope this helps you out!
